
(defun baris-theme ()
  (interactive "")
  (set-cursor-color "#000000")
  (custom-set-faces
   '(default ((t (:background "#ffffff" :foreground "#000000"))))
   ;; '(ido-first-match ((t (:foreground "#33ff33"))))
   ;; '(ido-subdir ((t (:foreground "#4444ff"))))
   '(font-lock-comment-face ((t (:foreground "#229955"))))
   '(font-lock-string-face ((t (:foreground "#4444ff"))))
   '(font-lock-keyword-face ((t (:bold nil :foreground "#851565"))))
   '(font-lock-constant-face ((t (:bold t :foreground "#000000"))))
   '(font-lock-builtin-face ((t (:foreground "#851565"))))
   '(font-lock-type-face ((t (:foreground "#851565"))))
   '(font-lock-variable-name-face ((t (:foreground "#000000"))))
   '(font-lock-function-name-face ((t (:bold t :foreground "#000000"))))
   '(font-lock-warning-face ((t (:underline t :foreground "VioletRed"))))
   '(font-lock-negation-char-face ((t (:bold t :foreground "#000000"))))
   '(font-lock-preprocessor-face ((t (:bold t :foreground "#000000"))))))

(defun wombat-theme ()
  (interactive "")
  (set-background-color "#242424")
  (set-foreground-color "#f6f3e8")
  (set-cursor-color "#656565")
  (set-face-foreground 'font-lock-comment-face "#99968b")
  (set-face-italic-p 'font-lock-comment-face t)
  (set-face-foreground 'font-lock-doc-face "#99968b")
  (set-face-italic-p 'font-lock-doc-face t)
  (set-face-foreground 'font-lock-constant-face "#e5786d")
  (set-face-foreground 'font-lock-string-face "#95e454")
  (set-face-italic-p 'font-lock-string-face t)
  (set-face-foreground 'font-lock-variable-name-face "#cae682")
  (set-face-foreground 'font-lock-function-name-face "#cae682")
  (set-face-foreground 'font-lock-type-face "#cae682")
  (set-face-foreground 'font-lock-builtin-face "#8ac6f2")
  (set-face-foreground 'font-lock-keyword-face "#8ac6f2")
  (set-face-foreground 'font-lock-preprocessor-face "#e5786d")
  (set-face-foreground 'font-lock-negation-char-face "#e7f6da")
  (set-face-foreground 'link "#8ac6f2")
  (set-face-bold-p 'link t)
  (set-face-underline-p 'link t)
  (set-face-foreground 'show-paren-match "#f6f3e8")
  (set-face-background 'show-paren-match "#857b6f")
  (set-face-bold-p 'show-paren-match t)
  (set-face-foreground 'region "#f6f3e8")
  (set-face-background 'region "#444444")
  (set-face-foreground 'lazy-highlight "black")
  (set-face-background 'lazy-highlight "yellow"))

(provide 'theme)