
(defun theme-baris ()
  (interactive "")
  (set-cursor-color "#000000")
  (custom-set-faces
   '(default ((t (:background "#ffffff" :foreground "#000000"))))
   ;; '(ido-first-match ((t (:foreground "#33ff33"))))
   ;; '(ido-subdir ((t (:foreground "#4444ff"))))
   '(font-lock-comment-face ((t (:foreground "#229955"))))
   '(font-lock-string-face ((t (:foreground "#4444ff"))))
   '(font-lock-keyword-face ((t (:bold nil :foreground "#851565"))))
   '(font-lock-constant-face ((t (:bold t :foreground "#000000"))))
   '(font-lock-builtin-face ((t (:foreground "#851565"))))
   '(font-lock-type-face ((t (:foreground "#851565"))))
   '(font-lock-variable-name-face ((t (:foreground "#000000"))))
   '(font-lock-function-name-face ((t (:bold t :foreground "#000000"))))
   '(font-lock-warning-face ((t (:underline t :foreground "VioletRed"))))
   '(font-lock-negation-char-face ((t (:bold t :foreground "#000000"))))
   '(font-lock-preprocessor-face ((t (:bold t :foreground "#000000"))))))

(defun theme-wombat ()
  (interactive "")
  (set-cursor-color "#656565")
  (custom-set-faces
   '(default ((t (:background "#242424" :foreground "#f6f3e8"))))
   '(font-lock-comment-face ((t (:foreground "#99968b" :italic t))))
   '(font-lock-doc-face ((t (:foreground"#99968b" :italic t))))
   '(font-lock-constant-face ((t (:foreground "#e5786d"))))
   '(font-lock-string-face ((t (:foreground "#95e454" :italic t))))
   '(font-lock-variable-name-face ((t (:foreground "#cae682"))))
   '(font-lock-function-name-face ((t (:foreground "#cae682"))))
   '(font-lock-type-face ((t (:foreground "#cae682"))))
   '(font-lock-builtin-face ((t (:foreground "#8ac6f2"))))
   '(font-lock-keyword-face ((t (:foreground "#8ac6f2"))))
   '(font-lock-preprocessor-face ((t (:foreground "#e5786d"))))
   '(font-lock-negation-char-face ((t (:foreground "#e7f6da"))))
   '(link ((t (:foreground "#8ac6f2" :bold t :underline t))))
   '(show-paren-match ((t (:foreground "#f6f3e8" :background "#857b6f" :bold t))))
   '(region ((t (:foreground "#f6f3e8" :background "#444444"))))
   '(lazy-highlight ((t (:foreground "black" :background "yellow"))))))

(provide 'theme)